# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x04grpc\".\n\tParameter\x12\x0f\n\x07trainId\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\t\"\x16\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\x35\n\x07Predict\x12*\n\x07predict\x12\x0f.grpc.Parameter\x1a\x0c.grpc.Result\"\x00\x42&\n\x15\x63om.example.yjyt.grpcB\x0bGRPCServiceP\x01\x62\x06proto3')



_PARAMETER = DESCRIPTOR.message_types_by_name['Parameter']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Parameter)
  })
_sym_db.RegisterMessage(Parameter)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Result)
  })
_sym_db.RegisterMessage(Result)

_PREDICT = DESCRIPTOR.services_by_name['Predict']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.example.yjyt.grpcB\013GRPCServiceP\001'
  _PARAMETER._serialized_start=23
  _PARAMETER._serialized_end=69
  _RESULT._serialized_start=71
  _RESULT._serialized_end=93
  _PREDICT._serialized_start=95
  _PREDICT._serialized_end=148
# @@protoc_insertion_point(module_scope)
